<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="90910" started-at="2017-10-22T05:32:37Z" finished-at="2017-10-22T05:34:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="90910" started-at="2017-10-22T05:32:37Z" finished-at="2017-10-22T05:34:08Z">
      <class name="com.snyder.test.regression.TestSelectProductUS1138">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.snyder.test.regression.TestSelectProductUS1138@5cb9f472]" name="setUp" is-config="true" duration-ms="19216" started-at="2017-10-22T11:02:37Z" finished-at="2017-10-22T11:02:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testAddProductTC1458()[pri:0, instance:com.snyder.test.regression.TestSelectProductUS1138@5cb9f472]" name="testAddProductTC1458" duration-ms="71675" started-at="2017-10-22T11:02:56Z" finished-at="2017-10-22T11:04:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Redmi Note 4 (Gold, 64 GB)] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Redmi Note 4 (Gold, 64 GB)] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.snyder.test.regression.TestSelectProductUS1138.testAddProductTC1458(TestSelectProductUS1138.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddProductTC1458 -->
      </class> <!-- com.snyder.test.regression.TestSelectProductUS1138 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
